ENTRY_NR(void, ActiveTexture, (GLenum texture), (texture), 4)
ENTRY_NR(void, AlphaFunc, (GLenum func, GLclampf ref), (func, ref), 8)
ENTRY_NR(void, ArrayElement, (GLint i), (i), 4)
ENTRY_NR(void, Begin, (GLenum mode), (mode), 4)
ENTRY_NR(void, BindTexture, (GLenum target, GLuint texture), (target, texture), 8)
ENTRY_NR(void, BlendFunc, (GLenum sfactor, GLenum dfactor), (sfactor, dfactor), 8)
ENTRY_NR(void, BlendFuncSeparate, (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha), (sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha), 16)
ENTRY_NR(void, CallList, (GLuint list), (list), 4)
ENTRY_NR(void, CallLists, (GLsizei n, GLenum type, const GLvoid *lists), (n, type, lists), 12)
ENTRY_NR(void, Clear, (GLbitfield mask), (mask), 4)
ENTRY_NR(void, ClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, ClearDepth, (GLclampd depth), (depth), 8)
ENTRY_NR(void, ClearStencil, (GLint s), (s), 4)
ENTRY_NR(void, ClientActiveTexture, (GLenum texture), (texture), 4)
ENTRY_NR(void, ClipPlane, (GLenum plane, const GLdouble *equation), (plane, equation), 8)
ENTRY_NR(void, Color3b, (GLbyte red, GLbyte green, GLbyte blue), (red, green, blue), 12)
ENTRY_NR(void, Color3bv, (const GLbyte *v), (v), 4)
ENTRY_NR(void, Color3d, (GLdouble red, GLdouble green, GLdouble blue), (red, green, blue), 24)
ENTRY_NR(void, Color3dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Color3f, (GLfloat red, GLfloat green, GLfloat blue), (red, green, blue), 12)
ENTRY_NR(void, Color3fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Color3i, (GLint red, GLint green, GLint blue), (red, green, blue), 12)
ENTRY_NR(void, Color3iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Color3s, (GLshort red, GLshort green, GLshort blue), (red, green, blue), 12)
ENTRY_NR(void, Color3sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, Color3ub, (GLubyte red, GLubyte green, GLubyte blue), (red, green, blue), 12)
ENTRY_NR(void, Color3ubv, (const GLubyte *v), (v), 4)
ENTRY_NR(void, Color3ui, (GLuint red, GLuint green, GLuint blue), (red, green, blue), 12)
ENTRY_NR(void, Color3uiv, (const GLuint *v), (v), 4)
ENTRY_NR(void, Color3us, (GLushort red, GLushort green, GLushort blue), (red, green, blue), 12)
ENTRY_NR(void, Color3usv, (const GLushort *v), (v), 4)
ENTRY_NR(void, Color4b, (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4bv, (const GLbyte *v), (v), 4)
ENTRY_NR(void, Color4d, (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha), (red, green, blue, alpha), 32)
ENTRY_NR(void, Color4dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Color4f, (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Color4i, (GLint red, GLint green, GLint blue, GLint alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Color4s, (GLshort red, GLshort green, GLshort blue, GLshort alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, Color4ub, (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4ubv, (const GLubyte *v), (v), 4)
ENTRY_NR(void, Color4ui, (GLuint red, GLuint green, GLuint blue, GLuint alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4uiv, (const GLuint *v), (v), 4)
ENTRY_NR(void, Color4us, (GLushort red, GLushort green, GLushort blue, GLushort alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, Color4usv, (const GLushort *v), (v), 4)
ENTRY_NR(void, ColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha), (red, green, blue, alpha), 16)
ENTRY_NR(void, ColorMaterial, (GLenum face, GLenum mode), (face, mode), 8)
ENTRY_NR(void, ColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr), (size, type, stride, ptr), 16)
ENTRY_NR(void, CompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data), (target, level, internalformat, width, height, border, imageSize, data), 32)
ENTRY_NR(void, CompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data), (target, level, xoffset, yoffset, width, height, format, imageSize, data), 36)
ENTRY_NR(void, CopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height), (target, level, xoffset, yoffset, x, y, width, height), 32)
ENTRY_NR(void, CullFace, (GLenum mode), (mode), 4)
ENTRY_NR(void, DeleteLists, (GLuint list, GLsizei range), (list, range), 8)
ENTRY_NR(void, DeleteTextures, (GLsizei n, const GLuint *textures), (n, textures), 8)
ENTRY_NR(void, DepthFunc, (GLenum func), (func), 4)
ENTRY_NR(void, DepthMask, (GLboolean flag), (flag), 4)
ENTRY_NR(void, DepthRange, (GLclampd near_val, GLclampd far_val), (near_val, far_val), 16)
ENTRY_NR(void, Disable, (GLenum cap), (cap), 4)
ENTRY_NR(void, DisableClientState, (GLenum cap), (cap), 4)
ENTRY_NR(void, DrawArrays, (GLenum mode, GLint first, GLsizei count), (mode, first, count), 12)
ENTRY_NR(void, DrawBuffer, (GLenum mode), (mode), 4)
ENTRY_NR(void, DrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices), (mode, count, type, indices), 16)
ENTRY_NR(void, DrawRangeElements, (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices), (mode, start, end, count, type, indices), 24)
ENTRY_NR(void, EdgeFlag, (GLboolean flag), (flag), 4)
ENTRY_NR(void, EdgeFlagPointer, (GLsizei stride, const GLvoid *ptr), (stride, ptr), 8)
ENTRY_NR(void, EdgeFlagv, (const GLboolean *flag), (flag), 4)
ENTRY_NR(void, Enable, (GLenum cap), (cap), 4)
ENTRY_NR(void, EnableClientState, (GLenum cap), (cap), 4)
ENTRY_NR(void, End, (void), (), 0)
ENTRY_NR(void, EndList, (void), (), 0)
ENTRY_NR(void, Finish, (void), (), 0)
ENTRY_NR(void, Flush, (void), (), 0)
ENTRY_NR(void, FogCoordd, (GLdouble c), (c), 8)
ENTRY_NR(void, FogCoorddv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, FogCoordf, (GLfloat c), (c), 4)
ENTRY_NR(void, FogCoordfv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, FogCoordPointer, (GLenum type, GLsizei stride, const GLvoid *ptr), (type, stride, ptr), 12)
ENTRY_NR(void, Fogf, (GLenum pname, GLfloat param), (pname, param), 8)
ENTRY_NR(void, Fogfv, (GLenum pname, const GLfloat *params), (pname, params), 8)
ENTRY_NR(void, Fogi, (GLenum pname, GLint param), (pname, param), 8)
ENTRY_NR(void, Fogiv, (GLenum pname, const GLint *params), (pname, params), 8)
ENTRY_NR(void, FrontFace, (GLenum mode), (mode), 4)
ENTRY_NR(void, Frustum, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val), (left, right, bottom, top, near_val, far_val), 48)
ENTRY_RV(GLuint, GenLists, (GLsizei range), (range), 4)
ENTRY_NR(void, GenTextures, (GLsizei n, GLuint *textures), (n, textures), 8)
ENTRY_NR(void, GetBooleanv, (GLenum pname, GLboolean *params), (pname, params), 8)
ENTRY_NR(void, GetCompressedTexImage, (GLenum target, GLint lod, GLvoid *img), (target, lod, img), 12)
ENTRY_NR(void, GetDoublev, (GLenum pname, GLdouble *params), (pname, params), 8)
ENTRY_RV(GLenum, GetError, (void), (), 0)
ENTRY_NR(void, GetFloatv, (GLenum pname, GLfloat *params), (pname, params), 8)
ENTRY_NR(void, GetIntegerv, (GLenum pname, GLint *params), (pname, params), 8)
ENTRY_RV(const GLubyte *, GetString, (GLenum name), (name), 4)
ENTRY_NR(void, GetTexImage, (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels), (target, level, format, type, pixels), 20)
ENTRY_NR(void, GetTexLevelParameterfv, (GLenum target, GLint level, GLenum pname, GLfloat *params), (target, level, pname, params), 16)
ENTRY_NR(void, GetTexLevelParameteriv, (GLenum target, GLint level, GLenum pname, GLint *params), (target, level, pname, params), 16)
ENTRY_NR(void, Hint, (GLenum target, GLenum mode), (target, mode), 8)
ENTRY_NR(void, InterleavedArrays, (GLenum format, GLsizei stride, const GLvoid *pointer), (format, stride, pointer), 12)
ENTRY_RV(GLboolean, IsEnabled, (GLenum cap), (cap), 4)
ENTRY_RV(GLboolean, IsList, (GLuint list), (list), 4)
ENTRY_RV(GLboolean, IsTexture, (GLuint texture), (texture), 4)
ENTRY_NR(void, LightModelf, (GLenum pname, GLfloat param), (pname, param), 8)
ENTRY_NR(void, LightModelfv, (GLenum pname, const GLfloat *params), (pname, params), 8)
ENTRY_NR(void, LightModeli, (GLenum pname, GLint param), (pname, param), 8)
ENTRY_NR(void, LightModeliv, (GLenum pname, const GLint *params), (pname, params), 8)
ENTRY_NR(void, Lightf, (GLenum light, GLenum pname, GLfloat param), (light, pname, param), 12)
ENTRY_NR(void, Lightfv, (GLenum light, GLenum pname, const GLfloat *params), (light, pname, params), 12)
ENTRY_NR(void, Lighti, (GLenum light, GLenum pname, GLint param), (light, pname, param), 12)
ENTRY_NR(void, Lightiv, (GLenum light, GLenum pname, const GLint *params), (light, pname, params), 12)
ENTRY_NR(void, ListBase, (GLuint base), (base), 4)
ENTRY_NR(void, LoadIdentity, (void), (), 0)
ENTRY_NR(void, LoadMatrixd, (const GLdouble *m), (m), 4)
ENTRY_NR(void, LoadMatrixf, (const GLfloat *m), (m), 4)
ENTRY_NR(void, LockArraysEXT, (GLint first, GLsizei count), (first, count), 8)
ENTRY_NR(void, Materialf, (GLenum face, GLenum pname, GLfloat param), (face, pname, param), 12)
ENTRY_NR(void, Materialfv, (GLenum face, GLenum pname, const GLfloat *params), (face, pname, params), 12)
ENTRY_NR(void, Materiali, (GLenum face, GLenum pname, GLint param), (face, pname, param), 12)
ENTRY_NR(void, Materialiv, (GLenum face, GLenum pname, const GLint *params), (face, pname, params), 12)
ENTRY_NR(void, MatrixMode, (GLenum mode), (mode), 4)
ENTRY_NR(void, MultMatrixd, (const GLdouble *m), (m), 4)
ENTRY_NR(void, MultMatrixf, (const GLfloat *m), (m), 4)
ENTRY_NR(void, MultiTexCoord1d, (GLenum target, GLdouble s), (target, s), 12)
ENTRY_NR(void, MultiTexCoord1dv, (GLenum target, const GLdouble *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord1f, (GLenum target, GLfloat s), (target, s), 8)
ENTRY_NR(void, MultiTexCoord1fv, (GLenum target, const GLfloat *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord1i, (GLenum target, GLint s), (target, s), 8)
ENTRY_NR(void, MultiTexCoord1iv, (GLenum target, const GLint *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord1s, (GLenum target, GLshort s), (target, s), 8)
ENTRY_NR(void, MultiTexCoord1sv, (GLenum target, const GLshort *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord2d, (GLenum target, GLdouble s, GLdouble t), (target, s, t), 20)
ENTRY_NR(void, MultiTexCoord2dv, (GLenum target, const GLdouble *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord2f, (GLenum target, GLfloat s, GLfloat t), (target, s, t), 12)
ENTRY_NR(void, MultiTexCoord2fv, (GLenum target, const GLfloat *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord2i, (GLenum target, GLint s, GLint t), (target, s, t), 12)
ENTRY_NR(void, MultiTexCoord2iv, (GLenum target, const GLint *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord2s, (GLenum target, GLshort s, GLshort t), (target, s, t), 12)
ENTRY_NR(void, MultiTexCoord2sv, (GLenum target, const GLshort *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord3d, (GLenum target, GLdouble s, GLdouble t, GLdouble r), (target, s, t, r), 28)
ENTRY_NR(void, MultiTexCoord3dv, (GLenum target, const GLdouble *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord3f, (GLenum target, GLfloat s, GLfloat t, GLfloat r), (target, s, t, r), 16)
ENTRY_NR(void, MultiTexCoord3fv, (GLenum target, const GLfloat *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord3i, (GLenum target, GLint s, GLint t, GLint r), (target, s, t, r), 16)
ENTRY_NR(void, MultiTexCoord3iv, (GLenum target, const GLint *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord3s, (GLenum target, GLshort s, GLshort t, GLshort r), (target, s, t, r), 16)
ENTRY_NR(void, MultiTexCoord3sv, (GLenum target, const GLshort *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord4d, (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q), (target, s, t, r, q), 36)
ENTRY_NR(void, MultiTexCoord4dv, (GLenum target, const GLdouble *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord4f, (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q), (target, s, t, r, q), 20)
ENTRY_NR(void, MultiTexCoord4fv, (GLenum target, const GLfloat *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord4i, (GLenum target, GLint s, GLint t, GLint r, GLint q), (target, s, t, r, q), 20)
ENTRY_NR(void, MultiTexCoord4iv, (GLenum target, const GLint *v), (target, v), 8)
ENTRY_NR(void, MultiTexCoord4s, (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q), (target, s, t, r, q), 20)
ENTRY_NR(void, MultiTexCoord4sv, (GLenum target, const GLshort *v), (target, v), 8)
ENTRY_NR(void, NewList, (GLuint list, GLenum mode), (list, mode), 8)
ENTRY_NR(void, Normal3b, (GLbyte nx, GLbyte ny, GLbyte nz), (nx, ny, nz), 12)
ENTRY_NR(void, Normal3bv, (const GLbyte *v), (v), 4)
ENTRY_NR(void, Normal3d, (GLdouble nx, GLdouble ny, GLdouble nz), (nx, ny, nz), 24)
ENTRY_NR(void, Normal3dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Normal3f, (GLfloat nx, GLfloat ny, GLfloat nz), (nx, ny, nz), 12)
ENTRY_NR(void, Normal3fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Normal3i, (GLint nx, GLint ny, GLint nz), (nx, ny, nz), 12)
ENTRY_NR(void, Normal3iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Normal3s, (GLshort nx, GLshort ny, GLshort nz), (nx, ny, nz), 12)
ENTRY_NR(void, Normal3sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, NormalPointer, (GLenum type, GLsizei stride, const GLvoid *ptr), (type, stride, ptr), 12)
ENTRY_NR(void, Ortho, (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val), (left, right, bottom, top, near_val, far_val), 48)
ENTRY_NR(void, PixelStoref, (GLenum pname, GLfloat param), (pname, param), 8)
ENTRY_NR(void, PixelStorei, (GLenum pname, GLint param), (pname, param), 8)
ENTRY_NR(void, PolygonMode, (GLenum face, GLenum mode), (face, mode), 8)
ENTRY_NR(void, PolygonOffset, (GLfloat factor, GLfloat units), (factor, units), 8)
ENTRY_NR(void, PolygonOffsetEXT, (GLfloat factor, GLfloat bias), (factor, bias), 8)
ENTRY_NR(void, PopAttrib, (void), (), 0)
ENTRY_NR(void, PopClientAttrib, (void), (), 0)
ENTRY_NR(void, PopMatrix, (void), (), 0)
ENTRY_NR(void, PushAttrib, (GLbitfield mask), (mask), 4)
ENTRY_NR(void, PushClientAttrib, (GLbitfield mask), (mask), 4)
ENTRY_NR(void, PushMatrix, (void), (), 0)
ENTRY_NR(void, ReadBuffer, (GLenum mode), (mode), 4)
ENTRY_NR(void, ReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels), (x, y, width, height, format, type, pixels), 28)
ENTRY_NR(void, Rectd, (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2), (x1, y1, x2, y2), 32)
ENTRY_NR(void, Rectdv, (const GLdouble *v1, const GLdouble *v2), (v1, v2), 8)
ENTRY_NR(void, Rectf, (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2), (x1, y1, x2, y2), 16)
ENTRY_NR(void, Rectfv, (const GLfloat *v1, const GLfloat *v2), (v1, v2), 8)
ENTRY_NR(void, Recti, (GLint x1, GLint y1, GLint x2, GLint y2), (x1, y1, x2, y2), 16)
ENTRY_NR(void, Rectiv, (const GLint *v1, const GLint *v2), (v1, v2), 8)
ENTRY_NR(void, Rects, (GLshort x1, GLshort y1, GLshort x2, GLshort y2), (x1, y1, x2, y2), 16)
ENTRY_NR(void, Rectsv, (const GLshort *v1, const GLshort *v2), (v1, v2), 8)
ENTRY_NR(void, Rotated, (GLdouble angle, GLdouble x, GLdouble y, GLdouble z), (angle, x, y, z), 32)
ENTRY_NR(void, Rotatef, (GLfloat angle, GLfloat x, GLfloat y, GLfloat z), (angle, x, y, z), 16)
ENTRY_NR(void, Scaled, (GLdouble x, GLdouble y, GLdouble z), (x, y, z), 24)
ENTRY_NR(void, Scalef, (GLfloat x, GLfloat y, GLfloat z), (x, y, z), 12)
ENTRY_NR(void, Scissor, (GLint x, GLint y, GLsizei width, GLsizei height), (x, y, width, height), 16)
ENTRY_NR(void, SecondaryColor3b, (GLbyte red, GLbyte green, GLbyte blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3bv, (const GLbyte *v), (v), 4)
ENTRY_NR(void, SecondaryColor3d, (GLdouble red, GLdouble green, GLdouble blue), (red, green, blue), 24)
ENTRY_NR(void, SecondaryColor3dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, SecondaryColor3f, (GLfloat red, GLfloat green, GLfloat blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, SecondaryColor3i, (GLint red, GLint green, GLint blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3iv, (const GLint *v), (v), 4)
ENTRY_NR(void, SecondaryColor3s, (GLshort red, GLshort green, GLshort blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, SecondaryColor3ub, (GLubyte red, GLubyte green, GLubyte blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3ubv, (const GLubyte *v), (v), 4)
ENTRY_NR(void, SecondaryColor3ui, (GLuint red, GLuint green, GLuint blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3uiv, (const GLuint *v), (v), 4)
ENTRY_NR(void, SecondaryColor3us, (GLushort red, GLushort green, GLushort blue), (red, green, blue), 12)
ENTRY_NR(void, SecondaryColor3usv, (const GLushort *v), (v), 4)
ENTRY_NR(void, SecondaryColorPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr), (size, type, stride, ptr), 16)
ENTRY_NR(void, ShadeModel, (GLenum mode), (mode), 4)
ENTRY_NR(void, StencilFunc, (GLenum func, GLint ref, GLuint mask), (func, ref, mask), 12)
ENTRY_NR(void, StencilMask, (GLuint mask), (mask), 4)
ENTRY_NR(void, StencilOp, (GLenum fail, GLenum zfail, GLenum zpass), (fail, zfail, zpass), 12)
ENTRY_NR(void, TexCoord1d, (GLdouble s), (s), 8)
ENTRY_NR(void, TexCoord1dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, TexCoord1f, (GLfloat s), (s), 4)
ENTRY_NR(void, TexCoord1fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, TexCoord1i, (GLint s), (s), 4)
ENTRY_NR(void, TexCoord1iv, (const GLint *v), (v), 4)
ENTRY_NR(void, TexCoord1s, (GLshort s), (s), 4)
ENTRY_NR(void, TexCoord1sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, TexCoord2d, (GLdouble s, GLdouble t), (s, t), 16)
ENTRY_NR(void, TexCoord2dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, TexCoord2f, (GLfloat s, GLfloat t), (s, t), 8)
ENTRY_NR(void, TexCoord2fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, TexCoord2i, (GLint s, GLint t), (s, t), 8)
ENTRY_NR(void, TexCoord2iv, (const GLint *v), (v), 4)
ENTRY_NR(void, TexCoord2s, (GLshort s, GLshort t), (s, t), 8)
ENTRY_NR(void, TexCoord2sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, TexCoord3d, (GLdouble s, GLdouble t, GLdouble r), (s, t, r), 24)
ENTRY_NR(void, TexCoord3dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, TexCoord3f, (GLfloat s, GLfloat t, GLfloat r), (s, t, r), 12)
ENTRY_NR(void, TexCoord3fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, TexCoord3i, (GLint s, GLint t, GLint r), (s, t, r), 12)
ENTRY_NR(void, TexCoord3iv, (const GLint *v), (v), 4)
ENTRY_NR(void, TexCoord3s, (GLshort s, GLshort t, GLshort r), (s, t, r), 12)
ENTRY_NR(void, TexCoord3sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, TexCoord4d, (GLdouble s, GLdouble t, GLdouble r, GLdouble q), (s, t, r, q), 32)
ENTRY_NR(void, TexCoord4dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, TexCoord4f, (GLfloat s, GLfloat t, GLfloat r, GLfloat q), (s, t, r, q), 16)
ENTRY_NR(void, TexCoord4fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, TexCoord4i, (GLint s, GLint t, GLint r, GLint q), (s, t, r, q), 16)
ENTRY_NR(void, TexCoord4iv, (const GLint *v), (v), 4)
ENTRY_NR(void, TexCoord4s, (GLshort s, GLshort t, GLshort r, GLshort q), (s, t, r, q), 16)
ENTRY_NR(void, TexCoord4sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, TexCoordPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr), (size, type, stride, ptr), 16)
ENTRY_NR(void, TexEnvf, (GLenum target, GLenum pname, GLfloat param), (target, pname, param), 12)
ENTRY_NR(void, TexEnvfv, (GLenum target, GLenum pname, const GLfloat *params), (target, pname, params), 12)
ENTRY_NR(void, TexEnvi, (GLenum target, GLenum pname, GLint param), (target, pname, param), 12)
ENTRY_NR(void, TexEnviv, (GLenum target, GLenum pname, const GLint *params), (target, pname, params), 12)
ENTRY_NR(void, TexGend, (GLenum coord, GLenum pname, GLdouble param), (coord, pname, param), 16)
ENTRY_NR(void, TexGendv, (GLenum coord, GLenum pname, const GLdouble *params), (coord, pname, params), 12)
ENTRY_NR(void, TexGenf, (GLenum coord, GLenum pname, GLfloat param), (coord, pname, param), 12)
ENTRY_NR(void, TexGenfv, (GLenum coord, GLenum pname, const GLfloat *params), (coord, pname, params), 12)
ENTRY_NR(void, TexGeni, (GLenum coord, GLenum pname, GLint param), (coord, pname, param), 12)
ENTRY_NR(void, TexGeniv, (GLenum coord, GLenum pname, const GLint *params), (coord, pname, params), 12)
ENTRY_NR(void, TexImage1D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels), (target, level, internalFormat, width, border, format, type, pixels), 32)
ENTRY_NR(void, TexImage2D, (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels), (target, level, internalFormat, width, height, border, format, type, pixels), 36)
ENTRY_NR(void, TexParameterf, (GLenum target, GLenum pname, GLfloat param), (target, pname, param), 12)
ENTRY_NR(void, TexParameterfv, (GLenum target, GLenum pname, const GLfloat *params), (target, pname, params), 12)
ENTRY_NR(void, TexParameteri, (GLenum target, GLenum pname, GLint param), (target, pname, param), 12)
ENTRY_NR(void, TexParameteriv, (GLenum target, GLenum pname, const GLint *params), (target, pname, params), 12)
ENTRY_NR(void, TexSubImage1D, (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels), (target, level, xoffset, width, format, type, pixels), 28)
ENTRY_NR(void, TexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels), (target, level, xoffset, yoffset, width, height, format, type, pixels), 36)
ENTRY_NR(void, Translated, (GLdouble x, GLdouble y, GLdouble z), (x, y, z), 24)
ENTRY_NR(void, Translatef, (GLfloat x, GLfloat y, GLfloat z), (x, y, z), 12)
ENTRY_NR(void, UnlockArraysEXT, (void), (), 0)
ENTRY_NR(void, Vertex2d, (GLdouble x, GLdouble y), (x, y), 16)
ENTRY_NR(void, Vertex2dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Vertex2f, (GLfloat x, GLfloat y), (x, y), 8)
ENTRY_NR(void, Vertex2fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Vertex2i, (GLint x, GLint y), (x, y), 8)
ENTRY_NR(void, Vertex2iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Vertex2s, (GLshort x, GLshort y), (x, y), 8)
ENTRY_NR(void, Vertex2sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, Vertex3d, (GLdouble x, GLdouble y, GLdouble z), (x, y, z), 24)
ENTRY_NR(void, Vertex3dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Vertex3f, (GLfloat x, GLfloat y, GLfloat z), (x, y, z), 12)
ENTRY_NR(void, Vertex3fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Vertex3i, (GLint x, GLint y, GLint z), (x, y, z), 12)
ENTRY_NR(void, Vertex3iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Vertex3s, (GLshort x, GLshort y, GLshort z), (x, y, z), 12)
ENTRY_NR(void, Vertex3sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, Vertex4d, (GLdouble x, GLdouble y, GLdouble z, GLdouble w), (x, y, z, w), 32)
ENTRY_NR(void, Vertex4dv, (const GLdouble *v), (v), 4)
ENTRY_NR(void, Vertex4f, (GLfloat x, GLfloat y, GLfloat z, GLfloat w), (x, y, z, w), 16)
ENTRY_NR(void, Vertex4fv, (const GLfloat *v), (v), 4)
ENTRY_NR(void, Vertex4i, (GLint x, GLint y, GLint z, GLint w), (x, y, z, w), 16)
ENTRY_NR(void, Vertex4iv, (const GLint *v), (v), 4)
ENTRY_NR(void, Vertex4s, (GLshort x, GLshort y, GLshort z, GLshort w), (x, y, z, w), 16)
ENTRY_NR(void, Vertex4sv, (const GLshort *v), (v), 4)
ENTRY_NR(void, VertexPointer, (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr), (size, type, stride, ptr), 16)
ENTRY_NR(void, Viewport, (GLint x, GLint y, GLsizei width, GLsizei height), (x, y, width, height), 16)
